"""initial schema

Revision ID: 0977abb4efbc
Revises: 
Create Date: 2026-03-15 20:12:57.754804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0977abb4efbc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('audit_status', sa.String(length=50), nullable=True),
    sa.Column('auditors', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('launched_at', sa.Date(), nullable=True),
    sa.Column('integration', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('yield_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('tokens', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('apy_current', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('apy_7d_avg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('apy_30d_avg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('tvl_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('min_deposit', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('lock_period_days', sa.Integer(), nullable=True),
    sa.Column('risk_tier', sa.String(length=20), nullable=True),
    sa.Column('deposit_address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yield_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('apy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('tvl_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('snapshot_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['yield_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yield_snapshots')
    op.drop_table('yield_opportunities')
    op.drop_table('protocols')
    # ### end Alembic commands ###
