"""add indexes and constraints

Revision ID: 13c42045b4b4
Revises: 0977abb4efbc
Create Date: 2026-03-15 20:23:57.316904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c42045b4b4'
down_revision: Union[str, Sequence[str], None] = '0977abb4efbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yield_opportunities', 'protocol_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('yield_opportunities', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_yield_opportunities_external_id'), 'yield_opportunities', ['external_id'], unique=True)
    op.create_index('ix_yield_opportunities_protocol_id', 'yield_opportunities', ['protocol_id'], unique=False)
    op.drop_constraint(op.f('yield_opportunities_protocol_id_fkey'), 'yield_opportunities', type_='foreignkey')
    op.create_foreign_key(None, 'yield_opportunities', 'protocols', ['protocol_id'], ['id'], ondelete='CASCADE')
    op.alter_column('yield_snapshots', 'opportunity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_yield_snapshots_opportunity_id', 'yield_snapshots', ['opportunity_id'], unique=False)
    op.create_index('ix_yield_snapshots_snapshot_at', 'yield_snapshots', ['snapshot_at'], unique=False)
    op.drop_constraint(op.f('yield_snapshots_opportunity_id_fkey'), 'yield_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'yield_snapshots', 'yield_opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yield_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('yield_snapshots_opportunity_id_fkey'), 'yield_snapshots', 'yield_opportunities', ['opportunity_id'], ['id'])
    op.drop_index('ix_yield_snapshots_snapshot_at', table_name='yield_snapshots')
    op.drop_index('ix_yield_snapshots_opportunity_id', table_name='yield_snapshots')
    op.alter_column('yield_snapshots', 'opportunity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'yield_opportunities', type_='foreignkey')
    op.create_foreign_key(op.f('yield_opportunities_protocol_id_fkey'), 'yield_opportunities', 'protocols', ['protocol_id'], ['id'])
    op.drop_index('ix_yield_opportunities_protocol_id', table_name='yield_opportunities')
    op.drop_index(op.f('ix_yield_opportunities_external_id'), table_name='yield_opportunities')
    op.alter_column('yield_opportunities', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('yield_opportunities', 'protocol_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
