"""add yield_opportunities performance indexes

Revision ID: 279c97e4360e
Revises: 44a9c99ee496
Create Date: 2026-03-22 10:09:47.673803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279c97e4360e'
down_revision: Union[str, Sequence[str], None] = '44a9c99ee496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_yield_opp_active_apy', 'yield_opportunities', ['is_active', 'apy_current'], unique=False)
    op.create_index('ix_yield_opp_active_tvl', 'yield_opportunities', ['is_active', 'tvl_usd'], unique=False)
    op.create_index('ix_yield_opp_category', 'yield_opportunities', ['category'], unique=False)
    op.create_index('ix_yield_opp_extra_data', 'yield_opportunities', ['extra_data'], unique=False, postgresql_using='gin')
    op.create_index('ix_yield_opp_tokens', 'yield_opportunities', ['tokens'], unique=False, postgresql_using='gin')
    op.create_unique_constraint('uq_yield_opportunities_protocol_external', 'yield_opportunities', ['protocol_id', 'external_id'])
    op.create_index('ix_yield_snapshots_snapshot_at', 'yield_snapshots', ['snapshot_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_yield_snapshots_snapshot_at', table_name='yield_snapshots')
    op.drop_constraint('uq_yield_opportunities_protocol_external', 'yield_opportunities', type_='unique')
    op.drop_index('ix_yield_opp_tokens', table_name='yield_opportunities', postgresql_using='gin')
    op.drop_index('ix_yield_opp_extra_data', table_name='yield_opportunities', postgresql_using='gin')
    op.drop_index('ix_yield_opp_category', table_name='yield_opportunities')
    op.drop_index('ix_yield_opp_active_tvl', table_name='yield_opportunities')
    op.drop_index('ix_yield_opp_active_apy', table_name='yield_opportunities')
    # ### end Alembic commands ###
