"""add apy_realized to user_positions

Revision ID: 2a3fd533d6f5
Revises: 4e38f5e799c8
Create Date: 2026-03-26 11:07:27.696502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3fd533d6f5'
down_revision: Union[str, Sequence[str], None] = '4e38f5e799c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_positions', sa.Column('apy_realized', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_positions', 'apy_realized')
    # ### end Alembic commands ###
