"""replace separate snapshot indexes with composite index

Revision ID: 44a9c99ee496
Revises: a1b2c3d4e5f6
Create Date: 2026-03-21 19:08:57.888685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a9c99ee496'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yield_snapshots_opportunity_id'), table_name='yield_snapshots')
    op.drop_index(op.f('ix_yield_snapshots_snapshot_at'), table_name='yield_snapshots')
    op.create_index('ix_yield_snapshots_opp_snapshot', 'yield_snapshots', ['opportunity_id', 'snapshot_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_yield_snapshots_opp_snapshot', table_name='yield_snapshots')
    op.create_index(op.f('ix_yield_snapshots_snapshot_at'), 'yield_snapshots', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_yield_snapshots_opportunity_id'), 'yield_snapshots', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###
