"""add missing indexes

Revision ID: 4e38f5e799c8
Revises: 279c97e4360e
Create Date: 2026-03-25 22:47:16.905895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e38f5e799c8'
down_revision: Union[str, Sequence[str], None] = '279c97e4360e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_positions_wallet_protocol', 'user_positions', ['wallet_address', 'protocol_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_positions_wallet_protocol', table_name='user_positions')
    # ### end Alembic commands ###
