"""add position PnL and APY fields

Revision ID: 7375bfa9b6a3
Revises: f30932ee4ab7
Create Date: 2026-03-21 14:40:08.988188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7375bfa9b6a3'
down_revision: Union[str, Sequence[str], None] = 'f30932ee4ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_positions', sa.Column('initial_deposit_usd', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('user_positions', sa.Column('opened_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user_positions', sa.Column('held_days', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('user_positions', sa.Column('apy', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('user_positions', sa.Column('is_closed', sa.Boolean(), nullable=True))
    op.add_column('user_positions', sa.Column('closed_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('user_positions', sa.Column('close_value_usd', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('user_positions', sa.Column('token_symbol', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_positions', 'token_symbol')
    op.drop_column('user_positions', 'close_value_usd')
    op.drop_column('user_positions', 'closed_at')
    op.drop_column('user_positions', 'is_closed')
    op.drop_column('user_positions', 'apy')
    op.drop_column('user_positions', 'held_days')
    op.drop_column('user_positions', 'opened_at')
    op.drop_column('user_positions', 'initial_deposit_usd')
    # ### end Alembic commands ###
