"""Add tracked wallets and user position tables

Revision ID: bfdbcae5c622
Revises: 13c42045b4b4
Create Date: 2026-03-21 11:12:39.244663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfdbcae5c622'
down_revision: Union[str, Sequence[str], None] = '13c42045b4b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('first_seen_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_fetched_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_wallets_wallet_address'), 'tracked_wallets', ['wallet_address'], unique=True)
    op.create_table('user_position_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('protocol_slug', sa.String(length=50), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tx_signature', sa.String(length=255), nullable=True),
    sa.Column('event_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_signature')
    )
    op.create_index('ix_user_position_events_wallet', 'user_position_events', ['wallet_address'], unique=False)
    op.create_index(op.f('ix_user_position_events_wallet_address'), 'user_position_events', ['wallet_address'], unique=False)
    op.create_table('user_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('protocol_slug', sa.String(length=50), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('deposit_amount_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pnl_usd', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('snapshot_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_positions_wallet_external', 'user_positions', ['wallet_address', 'external_id'], unique=False)
    op.create_index('ix_user_positions_wallet_snapshot', 'user_positions', ['wallet_address', 'snapshot_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_positions_wallet_snapshot', table_name='user_positions')
    op.drop_index('ix_user_positions_wallet_external', table_name='user_positions')
    op.drop_table('user_positions')
    op.drop_index(op.f('ix_user_position_events_wallet_address'), table_name='user_position_events')
    op.drop_index('ix_user_position_events_wallet', table_name='user_position_events')
    op.drop_table('user_position_events')
    op.drop_index(op.f('ix_tracked_wallets_wallet_address'), table_name='tracked_wallets')
    op.drop_table('tracked_wallets')
    # ### end Alembic commands ###
