"""add enrichment columns

Revision ID: e651e12dc8d6
Revises: 7375bfa9b6a3
Create Date: 2026-03-21 16:55:42.825046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e651e12dc8d6'
down_revision: Union[str, Sequence[str], None] = '7375bfa9b6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yield_opportunities', sa.Column('max_leverage', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('yield_opportunities', sa.Column('utilization_pct', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('yield_opportunities', sa.Column('liquidity_available_usd', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('yield_opportunities', sa.Column('is_automated', sa.Boolean(), nullable=True))
    op.add_column('yield_opportunities', sa.Column('depeg', sa.Numeric(precision=10, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yield_opportunities', 'depeg')
    op.drop_column('yield_opportunities', 'is_automated')
    op.drop_column('yield_opportunities', 'liquidity_available_usd')
    op.drop_column('yield_opportunities', 'utilization_pct')
    op.drop_column('yield_opportunities', 'max_leverage')
    # ### end Alembic commands ###
