"""add protocol_name to yield_opportunities

Revision ID: f30932ee4ab7
Revises: bfdbcae5c622
Create Date: 2026-03-21 11:36:21.725927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30932ee4ab7'
down_revision: Union[str, Sequence[str], None] = 'bfdbcae5c622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_position_events_wallet'), table_name='user_position_events')
    op.add_column('yield_opportunities', sa.Column('protocol_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yield_opportunities', 'protocol_name')
    op.create_index(op.f('ix_user_position_events_wallet'), 'user_position_events', ['wallet_address'], unique=False)
    # ### end Alembic commands ###
